name: store_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5 # state management
  firebase_core: ^2.18.0 # add firebase
  firebase_auth: ^4.11.0 # firebase لعمل تسجيل الدخول باستخدام
  google_sign_in: ^6.1.5 # لتسجيل الدخول باستخدام جوجل
  flutter_svg: ^2.0.7 # svg لاضافه صور بصيغه 
  cloud_firestore: ^4.11.0 # firebase الخاص ب firestore بيتم استخدمه لتخزين الداتا في ال
  intl: ^0.18.1 # للتعامل مع التواريخ والوقت
  image_picker: ^1.0.4 # لاختيار الصور من معرض الصور في الجهاز أو التقاط صورة جديدة باستخدام الكاميرا
  firebase_storage: ^11.4.0 # Firebase Storage تسمح بتخزين ملفاتك (مثل الصور والفيديوهات والمستندات) في
  # email_validator: ^2.1.17 # بيستخدم لعمل تحقق ان البريد وكلمه السر مكتوبه بشكل صحيح او لا

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
