// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh3ihkazQFiv-HfsdGmOiORlV4j0kU1Vs',
    appId: '1:199660311361:web:74d7b04fbb517457f847c0',
    messagingSenderId: '199660311361',
    projectId: 'store-app-44415',
    authDomain: 'store-app-44415.firebaseapp.com',
    storageBucket: 'store-app-44415.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOf5fR8Z6VlgOOcVr7ebh8-UnoCmNLUHo',
    appId: '1:199660311361:android:ce7bfcec7960e5b6f847c0',
    messagingSenderId: '199660311361',
    projectId: 'store-app-44415',
    storageBucket: 'store-app-44415.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg4uDugXfD8yqSz-jFRzr-BtObf_fQn-Y',
    appId: '1:199660311361:ios:98c9a3267a75ca11f847c0',
    messagingSenderId: '199660311361',
    projectId: 'store-app-44415',
    storageBucket: 'store-app-44415.appspot.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg4uDugXfD8yqSz-jFRzr-BtObf_fQn-Y',
    appId: '1:199660311361:ios:b4abbad7c6a445c2f847c0',
    messagingSenderId: '199660311361',
    projectId: 'store-app-44415',
    storageBucket: 'store-app-44415.appspot.com',
    iosBundleId: 'com.example.storeApp.RunnerTests',
  );
}
